#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# 허스키를 사용하여 git에 commit을 push할 때 자동으로 다음 명령어를 실행해 잘 되는지 판단하게 할 수 있음
# npm run lint && npm run format

# lint-staged를 받았으면 package.json에서 설정을하고 다음 명령어를 허스키에 넣어둠
npx lint-staged
